### ISSUE TITLE
feat: add getModelParameters for various organisms

### ISSUE THREAD

**Issue by IVANDOMENZAIN** [SysBioChalmers/ecModels#20]
Include `getModelParameters` scripts (see this [PR](https://github.com/SysBioChalmers/GECKO/pull/76) for more info)for the following models as model-specific scripts:
- [x] YeastGEM
- [x] KmxGEM
- [x] iYali4
- [x] HumanGEM
- [x] iML1515

**Comment by mihai-sysbio** [comment]
*KmxGEM* was missing the `.xml` on master. Now it exists, so let's see how the auto-run pipeline behaves.

*iYali* has a problem, perhaps my GECKO fork should be updated?
```
INFO:__main__:
        cd geckomat
        model = load('/home/jenkins/ecModels-dependencies/Yali-GEM/ModelFiles/mat/iYali.mat');
        model = model.model;
        modelname = 'ecYaliGEM';
        [ecModel, ecModel_batch] = enhanceGEM(model,'COBRA', modelname, '4.1.1');
        cd ../models
        save([modelname '/' modelname '.mat']','ecModel');
        save([modelname '/' modelname '_batch.mat'], 'ecModel_batch');
        quit
        
{ Unable to perform assignment with 0 elements on the right-hand side.

Error in manualModifications>otherChanges (line 425)
         rxn_id   = model.rxns{pos_rxn};

Error in manualModifications (line 113)
model = otherChanges(model);

Error in enhanceGEM (line 37)
[ecModel,modifications] = manualModifications(ecModel);
}
```

For *Human-GEM* I think we arrived to some conclusion wrt not providing any tissue GEMs, so there would be only one ecHuman-GEM which would make it fit with the rest of the pipeline, but I might be confused.

**Comment by IVANDOMENZAIN** [comment]
You're right @mihai-sysbio, for HumanGEM we're just thinking on adding the original general model into the ecModels pipeline.

**Comment by mihai-sysbio** [comment]
Haha sorry I moved the conversation on another issue since this was supposed to be focused on `getModelParameters`.
