### ISSUE TITLE
feat: automate version retrieving from models

### ISSUE THREAD

**Issue by IVANDOMENZAIN** [SysBioChalmers/ecModels#21]
It has been agreed that all original models' structures (version controlled or not) should be loaded from their corresponding `SBML` file. Currently, the version of the model can be obtained in several ways by the `ecModels` pipeline (e.g. read from a MATLAB structure or provided by the user). 

A generalized way to read the model's version is to parse it from the `<name>` or `<id>` fields in the `SBML` file. As an example, the model name and Ids lines for the `Kmx` and `iYali` models are provided here:

- model metaid="kmxGEM.xml" id="M_kmxGEM_v1_46_0_46_0" name="The Consensus Genome-Scale Metabolic Model of Kluyveromyces marxianus" fbc:strict="true"
- model metaid="iYali" id="iYali" name="Yarrowia_lipolytica-GEM_v4.1.1" fbc:strict="true"

As a solution, a python script can be developed in which the version is parsed from this file, trying it on both fields `<name>` or `<id>` and, if absent a default **v1.0.0** string is introduced

**Comment by IVANDOMENZAIN** [comment]
This issue has been partially addressed by [PR#113](https://github.com/SysBioChalmers/GECKO/pull/113) in GECKO. Model version can be parsed directly by GECKO either from the `name`, `id` or `version` fields.

**Comment by IVANDOMENZAIN** [comment]
For non-version controlled models, it is intended that the python runner script (for the automated pipeline) assigns a dummy version to the  model.

**Comment by mihai-sysbio** [comment]
Is there a specific reason we load the `.mat` file instead of the `.xml`? I'm consider of using the [xml_load](https://github.com/SysBioChalmers/RAVEN/blob/9070e7ea5c594dfd83ac0b5e4df6991d8f959da5/legacy/software/xml_toolbox/xml_load.m) function in the pipeline. Does this have something to do with fetching the version?

**Comment by IVANDOMENZAIN** [comment]
@mihai-sysbio, not really, `.xml` files be the ones that are loaded preferably, if available. Just use the `importModel` function in RAVEN instead of `xml_load`.

**Comment by mihai-sysbio** [comment]
Alright, switching from `.mat` to `.xml` is quite straighforward. I've done a preliminary test and it seems to work. For now, I'll revert the changes. Whenever we decide to start using `SBML` I can reimplement this.

**Comment by IVANDOMENZAIN** [comment]
The pipeline has switched to `.xml` files for non version-controlled models, instead of handling `.mat` files, in order to stick to standard good practices.
