### ISSUE TITLE
Branching system for new ecModels

### ISSUE THREAD

**Issue by IVANDOMENZAIN** [SysBioChalmers/ecModels#5]
This repo has already become an ecosystem, biology is complex in nature, but we can try to keep a sustainable and simple branching system. 

We should think about:

- simplicity (an easy-to-follow/visualize graph)
- clear set of permissions and PR criteria 
- Allow automated integration
- Storage (model files without original repo)

**Comment by mihai-sysbio** [comment]
I had to draft a branching scheme when writing the automation code.

There is a "big" branch called `updates`. This is where all the models are committed to.
Each GEM has its own branch under `updates` , where each version is another branch. And then, for each such version, there is another branch with the timestamp of the run. This timestamp gives the uniqueness needed, equivalent to a commit hash, but before the commit exists.
I'm not sure this is good - perhaps all updates could be dumped onto the same version branch.

Then, the PR target from this branch where new versions are committed can be anything - `master` sounds like a good choice.

Here's an example [for Yeast-GEM on the ecModels fork](https://github.com/mihai-sysbio/ecModels/pull/14)

**Comment by mihai-sysbio** [comment]
It seems the proposed branching scheme is good enough for now. Please reopen the issue if the discussion should continue.
