### ISSUE TITLE
Workflow failing on the eciYali step

### ISSUE THREAD

**Issue by IVANDOMENZAIN** [SysBioChalmers/ecModels#61]
In the latest long runs of the automated pipeline ([run1](https://github.com/SysBioChalmers/ecModels/runs/1962988229?check_suite_focus=true), [run2](https://github.com/SysBioChalmers/ecModels/runs/1939273128?check_suite_focus=true), [run3](https://github.com/SysBioChalmers/ecModels/runs/1937880817?check_suite_focus=true)) it has been observed an error in the MATLAB command for the `iYali` case. All of these errors point out to the same line (429) in the corresponding `manualModifications` script, however this script is much shorter for this case, which makes conclude that the pipeline is not substituting the `iYali`-specific scripts into GECKO, therefore an error pops-up in MATLAB and our pipeline is crashing.

Any ideas on how to solve this? I also think that we've seen happening before but don't remember so well.

**Comment by IVANDOMENZAIN** [comment]
@mihai-sysbio

**Comment by mihai-sysbio** [comment]
It seems that the Matlab code moving the files has no effect. I suspect what it has to do with the git command being slow, so the Matlab command is invoked before the git clone step finished. If so, then this is fixed by changing how the commands are invoked.

**Comment by mihai-sysbio** [comment]
It was a good idea to change `check_call` to `check_output`, but to solve the problem the base branch of the pipeline has to be different than the `pull_request_target` in `config.ini`. Things [look promissing in line 5](https://github.com/SysBioChalmers/ecModels/runs/1994246243?check_suite_focus=true#step:3:5)

> INFO:__main__:Pipeline started on branch fix/issues-with-scripts-folder

**Comment by mihai-sysbio** [comment]
Alright, this has been resolved.
